// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqhkocrkvdoxsvogqnbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxaGtvY3JrdmRveHN2b2dxbmJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzU5MTcsImV4cCI6MjA3MDgxMTkxN30.zCTXCqEInyKu7vXQoz_TJRF7sT6POk4KuGAw1UYdT9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});